version: '2'
services:
  web:
    build: ./
    container_name: lucaschmid.net
    volumes:
      - ./:/var/app
    ports:
      - 443:443
      - 80:80
    restart: always
    env_file: .env
  db:
    image: mongo
    volumes:
      - /data:/data/db

